In [3]:
a=range(0,15,3)
print(a)

range(0, 15, 3)


In [5]:
print(numpy.sqrt(1.21))

NameError: name 'numpy' is not defined

In [6]:
import numpy as np
print(np.sqrt(1.21))
print(np.cos(np.pi))
print(np.log(np.exp(5.2)))

1.1
-1.0
5.2


In [8]:
vec=np.array([1,2,3,4,5])
print(vec)

[1 2 3 4 5]


In [15]:
mat=np.array([[1,2],[2,3],[6,7]])
print(mat)
print("")
print(mat.T)

[[1 2]
 [2 3]
 [6 7]]

[[1 2 6]
 [2 3 7]]


In [20]:
vec1=np.arange(0,15)
print(vec1)
print("")
vec2=np.arange(0,5,10)
print(vec2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[0]


In [25]:
vec3=np.linspace(0,5,10)
print(vec3)
print(vec3.reshape(5,2))
vec3_res=vec3.reshape(5,2)
print(vec3_res)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [2]:
import numpy as np
rand_vec=np.random.rand(19)
print(rand_vec)

[0.04278192 0.15675087 0.31460557 0.12164441 0.47034844 0.35012207
 0.23178169 0.38786862 0.66584402 0.78403335 0.39723473 0.51572475
 0.58545377 0.97230613 0.51486535 0.38258616 0.70745066 0.26818617
 0.1304484 ]


In [3]:
print(rand_vec[6])

0.23178168796147236


In [4]:
print(rand_vec[2:6])

[0.31460557 0.12164441 0.47034844 0.35012207]


In [6]:
a_range=np.arange(0,15,3)
print(a_range)
print(rand_vec[a_range])

[ 0  3  6  9 12]
[0.04278192 0.12164441 0.23178169 0.78403335 0.58545377]


#now about Matrices

In [19]:
rand_mat=np.random.rand(5,5)
print(rand_mat)

[[0.9045267  0.04833656 0.26727298 0.1744607  0.29687128]
 [0.15837509 0.6416919  0.99406007 0.61128597 0.06549397]
 [0.5476382  0.86092927 0.69422066 0.15401718 0.40937594]
 [0.64204066 0.71076196 0.18961376 0.8668974  0.31409636]
 [0.43440648 0.53064123 0.48678333 0.66889894 0.95454982]]


In [20]:
print(rand_mat[1,2])
print("")
print(rand_mat[1][2])

0.22199266184129818

0.22199266184129818


In [21]:
print(rand_mat[0:2,1:3])

[[0.60219354 0.8024063 ]
 [0.33130423 0.22199266]]


In [22]:
#To cahnge some values

In [23]:
print(rand_vec)
rand_vec[3:5]=4
print(rand_vec)
rand_vec[3:5]=[1,2]
print(rand_vec)

[0.04278192 0.15675087 0.31460557 0.12164441 0.47034844 0.35012207
 0.23178169 0.38786862 0.66584402 0.78403335 0.39723473 0.51572475
 0.58545377 0.97230613 0.51486535 0.38258616 0.70745066 0.26818617
 0.1304484 ]
[0.04278192 0.15675087 0.31460557 4.         4.         0.35012207
 0.23178169 0.38786862 0.66584402 0.78403335 0.39723473 0.51572475
 0.58545377 0.97230613 0.51486535 0.38258616 0.70745066 0.26818617
 0.1304484 ]
[0.04278192 0.15675087 0.31460557 1.         2.         0.35012207
 0.23178169 0.38786862 0.66584402 0.78403335 0.39723473 0.51572475
 0.58545377 0.97230613 0.51486535 0.38258616 0.70745066 0.26818617
 0.1304484 ]


In [20]:
rand_mat[0:2,1:3]=0
print(rand_mat)     

[[0.9045267  0.         0.         0.1744607  0.29687128]
 [0.15837509 0.         0.         0.61128597 0.06549397]
 [0.5476382  0.86092927 0.69422066 0.15401718 0.40937594]
 [0.64204066 0.71076196 0.18961376 0.8668974  0.31409636]
 [0.43440648 0.53064123 0.48678333 0.66889894 0.95454982]]


In [40]:
##freak thing in python


In [28]:
sub_mat=rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:]=3
print(sub_mat)
print(rand_mat)


[[3. 3. 3.]
 [3. 3. 3.]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[3.         3.         3.         0.58741965 0.47440121]
 [3.         3.         3.         0.87740293 0.01655437]
 [0.14187871 0.82828851 0.05970947 0.39551558 0.86001023]
 [0.02613585 0.01524446 0.70835309 0.50110304 0.54736265]
 [0.23306936 0.1304634  0.35030894 0.34040948 0.56888556]]


In [21]:
sub_mat2=rand_mat[0:2,0:3].copy()
print(sub_mat2)
sub_mat2[:]=10
print(sub_mat2)
print(rand_mat)

[[0.9045267  0.         0.        ]
 [0.15837509 0.         0.        ]]
[[10. 10. 10.]
 [10. 10. 10.]]
[[0.9045267  0.         0.         0.1744607  0.29687128]
 [0.15837509 0.         0.         0.61128597 0.06549397]
 [0.5476382  0.86092927 0.69422066 0.15401718 0.40937594]
 [0.64204066 0.71076196 0.18961376 0.8668974  0.31409636]
 [0.43440648 0.53064123 0.48678333 0.66889894 0.95454982]]


In [1]:
#to access and change values using logicals


In [7]:
import numpy as np
rand_vec=np.random.randn(15)
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])



[ 0.08971419 -0.22853592  0.99131926 -1.2318888   0.71217311  1.04385203
 -0.21187764 -0.27829534  0.09444672 -0.7014236   0.55912395  0.19308964
  1.33386355  0.14421151  0.36183817]
[ True False  True False  True  True False False  True False  True  True
  True  True  True]
[0.08971419 0.99131926 0.71217311 1.04385203 0.09444672 0.55912395
 0.19308964 1.33386355 0.14421151 0.36183817]


In [12]:
rand_mat2=np.random.randn(7,5)
print(rand_mat2)
print(rand_mat2>0)
print(rand_mat2[rand_mat2>0])

[[-0.16567619  1.06032618  1.43100768 -0.34504666  0.88592067]
 [ 0.79121544 -2.19676803 -0.65639184  1.19563197  0.1229657 ]
 [ 0.46614783  0.18779361 -1.09615691 -0.01263526  0.85291724]
 [-1.22928448 -0.09750396  0.27820371  1.12581718  1.14558067]
 [ 0.73917312  0.54377685 -0.18245655  1.41787848 -0.09118284]
 [-0.86870089 -1.57944826  0.33627383  0.60951224 -0.31283863]
 [ 1.09467467 -0.44134089 -1.74467    -1.31304865 -0.83826641]]
[[False  True  True False  True]
 [ True False False  True  True]
 [ True  True False False  True]
 [False False  True  True  True]
 [ True  True False  True False]
 [False False  True  True False]
 [ True False False False False]]
[1.06032618 1.43100768 0.88592067 0.79121544 1.19563197 0.1229657
 0.46614783 0.18779361 0.85291724 0.27820371 1.12581718 1.14558067
 0.73917312 0.54377685 1.41787848 0.33627383 0.60951224 1.09467467]


In [14]:
print(rand_vec)
print('')
rand_vec[rand_vec>0]=5
print(rand_vec)

[ 0.08971419 -0.22853592  0.99131926 -1.2318888   0.71217311  1.04385203
 -0.21187764 -0.27829534  0.09444672 -0.7014236   0.55912395  0.19308964
  1.33386355  0.14421151  0.36183817]

[ 5.         -0.22853592  5.         -1.2318888   5.          5.
 -0.21187764 -0.27829534  5.         -0.7014236   5.          5.
  5.          5.          5.        ]


In [15]:
np.save('saved_file_name',rand_mat2)

In [22]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [24]:
load_vec=np.load('saved_file_name.npy')
print(load_vec)

[[-0.16567619  1.06032618  1.43100768 -0.34504666  0.88592067]
 [ 0.79121544 -2.19676803 -0.65639184  1.19563197  0.1229657 ]
 [ 0.46614783  0.18779361 -1.09615691 -0.01263526  0.85291724]
 [-1.22928448 -0.09750396  0.27820371  1.12581718  1.14558067]
 [ 0.73917312  0.54377685 -0.18245655  1.41787848 -0.09118284]
 [-0.86870089 -1.57944826  0.33627383  0.60951224 -0.31283863]
 [ 1.09467467 -0.44134089 -1.74467    -1.31304865 -0.83826641]]


In [26]:
load_zip=np.load('zipped_file_name.npz')
print(load_zip)

In [27]:
new_array=load_zip['rand_mat']
print(new_array)

[[0.9045267  0.         0.         0.1744607  0.29687128]
 [0.15837509 0.         0.         0.61128597 0.06549397]
 [0.5476382  0.86092927 0.69422066 0.15401718 0.40937594]
 [0.64204066 0.71076196 0.18961376 0.8668974  0.31409636]
 [0.43440648 0.53064123 0.48678333 0.66889894 0.95454982]]


In [32]:
new_array2=load_zip['rand_mat2']
print(new_array2)

[[-0.16567619  1.06032618  1.43100768 -0.34504666  0.88592067]
 [ 0.79121544 -2.19676803 -0.65639184  1.19563197  0.1229657 ]
 [ 0.46614783  0.18779361 -1.09615691 -0.01263526  0.85291724]
 [-1.22928448 -0.09750396  0.27820371  1.12581718  1.14558067]
 [ 0.73917312  0.54377685 -0.18245655  1.41787848 -0.09118284]
 [-0.86870089 -1.57944826  0.33627383  0.60951224 -0.31283863]
 [ 1.09467467 -0.44134089 -1.74467    -1.31304865 -0.83826641]]


In [33]:
print(load_zip['rand_mat'])

[[0.9045267  0.         0.         0.1744607  0.29687128]
 [0.15837509 0.         0.         0.61128597 0.06549397]
 [0.5476382  0.86092927 0.69422066 0.15401718 0.40937594]
 [0.64204066 0.71076196 0.18961376 0.8668974  0.31409636]
 [0.43440648 0.53064123 0.48678333 0.66889894 0.95454982]]


In [35]:
print(load_zip['rand_mat2'])

[[-0.16567619  1.06032618  1.43100768 -0.34504666  0.88592067]
 [ 0.79121544 -2.19676803 -0.65639184  1.19563197  0.1229657 ]
 [ 0.46614783  0.18779361 -1.09615691 -0.01263526  0.85291724]
 [-1.22928448 -0.09750396  0.27820371  1.12581718  1.14558067]
 [ 0.73917312  0.54377685 -0.18245655  1.41787848 -0.09118284]
 [-0.86870089 -1.57944826  0.33627383  0.60951224 -0.31283863]
 [ 1.09467467 -0.44134089 -1.74467    -1.31304865 -0.83826641]]


In [36]:
#to save/load ot as text file but only single array at a time


In [39]:
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt=np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)#orginal
print(rand_mat_txt)#loaded 

[[0.9045267  0.         0.         0.1744607  0.29687128]
 [0.15837509 0.         0.         0.61128597 0.06549397]
 [0.5476382  0.86092927 0.69422066 0.15401718 0.40937594]
 [0.64204066 0.71076196 0.18961376 0.8668974  0.31409636]
 [0.43440648 0.53064123 0.48678333 0.66889894 0.95454982]]
[[0.9045267  0.         0.         0.1744607  0.29687128]
 [0.15837509 0.         0.         0.61128597 0.06549397]
 [0.5476382  0.86092927 0.69422066 0.15401718 0.40937594]
 [0.64204066 0.71076196 0.18961376 0.8668974  0.31409636]
 [0.43440648 0.53064123 0.48678333 0.66889894 0.95454982]]


##Pandas


In [41]:
import pandas as pd
import numpy as np



In [45]:
mylist=[1.1,2.2,3.3,4.4,5.5]
myarray=np.array(mylist)


In [49]:
myseries1=pd.Series(mylist)
print(myseries1)

0    1.1
1    2.2
2    3.3
3    4.4
4    5.5
dtype: float64


In [50]:
myseries2=pd.Series(data=myarray)
print(myseries2)

0    1.1
1    2.2
2    3.3
3    4.4
4    5.5
dtype: float64


In [51]:
#to acces the indiviual entries it is same as list and numpy

In [53]:
print(myseries2[2])

3.3


In [79]:
mylabels=['first','second','third','fourth','fifth']
mylabelsup=['numbers']
myseries3=pd.Series(data=myarray,index=mylabels)
print(myseries3)          
          

first     1.1
second    2.2
third     3.3
fourth    4.4
fifth     5.5
dtype: float64


In [60]:
myseries4=pd.Series(myarray,mylabels)
print(myseries4)

first     1.1
second    2.2
third     3.3
fourth    4.4
fifth     5.5
dtype: float64


In [62]:
print(myseries4['fifth'])

5.5


In [69]:
myseries5=pd.Series([5.6,7.8,5.68,8.5,9.5],['first','third','fourth','fifth','sixth'])
print(myseries5)
print(myseries4+myseries5)

first     5.60
third     7.80
fourth    5.68
fifth     8.50
sixth     9.50
dtype: float64
fifth     14.00
first      6.70
fourth    10.08
second      NaN
sixth       NaN
third     11.10
dtype: float64


In [71]:
df1=pd.concat([myseries4,myseries5],axis=1,sort=False)
df1

0     1
first   1.1  5.60
second  2.2   NaN
third   3.3  7.80
fourth  4.4  5.68
fifth   5.5  8.50
sixth   NaN  9.50

In [74]:
df2=pd.DataFrame(np.random.randn(5,5))
df2

0         1         2         3         4
0  1.792475 -0.789895  2.231268 -2.250459 -0.652503
1  0.346874 -0.770591 -1.221765  1.050765  0.039116
2 -1.076664  0.485094 -0.917030 -0.622374 -0.909040
3  0.631138  0.195610 -0.665160 -0.557017  0.156356
4  0.849333  0.228235  0.544263 -2.076792  0.222703

In [83]:
df3=pd.DataFrame(np.random.randn(5,5),index=['first row','sec row','thr row','for row','fifth row'],columns=['first col','sec col','thr col','for col','fif col'])
df3


first col   sec col   thr col   for col   fif col
first row   0.500967 -0.138586 -0.063294  0.564966 -0.264764
sec row    -0.696496 -0.214863 -0.941346  2.304170 -0.265284
thr row    -2.426288 -1.586326 -1.079067  2.338292  1.274975
for row     0.162268  0.620766  0.514160 -0.017655 -1.486490
fifth row   2.294349  0.327749 -0.545991  2.078547 -0.670667

In [88]:
print(df3['sec col'])
print("")
df3[['sec col','thr col']]


first row   -0.138586
sec row     -0.214863
thr row     -1.586326
for row      0.620766
fifth row    0.327749
Name: sec col, dtype: float64



sec col   thr col
first row -0.138586 -0.063294
sec row   -0.214863 -0.941346
thr row   -1.586326 -1.079067
for row    0.620766  0.514160
fifth row  0.327749 -0.545991

In [89]:
df3['sec col']

first row   -0.138586
sec row     -0.214863
thr row     -1.586326
for row      0.620766
fifth row    0.327749
Name: sec col, dtype: float64

In [90]:
df3.loc['for row']

first col    0.162268
sec col      0.620766
thr col      0.514160
for col     -0.017655
fif col     -1.486490
Name: for row, dtype: float64

In [92]:
df3.iloc[2]

first col   -2.426288
sec col     -1.586326
thr col     -1.079067
for col      2.338292
fif col      1.274975
Name: thr row, dtype: float64

In [93]:
df3.loc[['first row','sec row'],['sec col','thr col']]

sec col   thr col
first row -0.138586 -0.063294
sec row   -0.214863 -0.941346

In [94]:
df3>0


first col  sec col  thr col  for col  fif col
first row       True    False    False     True    False
sec row        False    False    False     True    False
thr row        False    False    False     True     True
for row         True     True     True    False    False
fifth row       True     True    False     True    False

In [95]:
print(df3[df3>0])

           first col   sec col  thr col   for col   fif col
first row   0.500967       NaN      NaN  0.564966       NaN
sec row          NaN       NaN      NaN  2.304170       NaN
thr row          NaN       NaN      NaN  2.338292  1.274975
for row     0.162268  0.620766  0.51416       NaN       NaN
fifth row   2.294349  0.327749      NaN  2.078547       NaN


In [99]:
df3['sixth col']=np.random.rand(5,1)
df3

first col   sec col   thr col   for col   fif col  sixth col
first row   0.500967 -0.138586 -0.063294  0.564966  0.247865   0.721323
sec row    -0.696496 -0.214863 -0.941346  2.304170  0.561030   0.443285
thr row    -2.426288 -1.586326 -1.079067  2.338292  0.192024   0.439772
for row     0.162268  0.620766  0.514160 -0.017655  0.198702   0.154176
fifth row   2.294349  0.327749 -0.545991  2.078547  0.876584   0.461476

In [102]:
df3.drop('first col',axis=1,inplace=True)

In [104]:
df3

sec col   thr col   for col   fif col  sixth col
first row -0.138586 -0.063294  0.564966  0.247865   0.721323
sec row   -0.214863 -0.941346  2.304170  0.561030   0.443285
thr row   -1.586326 -1.079067  2.338292  0.192024   0.439772
for row    0.620766  0.514160 -0.017655  0.198702   0.154176
fifth row  0.327749 -0.545991  2.078547  0.876584   0.461476

In [105]:
df4=df3.drop('sec col',axis=1)
df4

thr col   for col   fif col  sixth col
first row -0.063294  0.564966  0.247865   0.721323
sec row   -0.941346  2.304170  0.561030   0.443285
thr row   -1.079067  2.338292  0.192024   0.439772
for row    0.514160 -0.017655  0.198702   0.154176
fifth row -0.545991  2.078547  0.876584   0.461476

In [107]:
df5=df3.drop('first row',axis=0)
df5

sec col   thr col   for col   fif col  sixth col
sec row   -0.214863 -0.941346  2.304170  0.561030   0.443285
thr row   -1.586326 -1.079067  2.338292  0.192024   0.439772
for row    0.620766  0.514160 -0.017655  0.198702   0.154176
fifth row  0.327749 -0.545991  2.078547  0.876584   0.461476

In [109]:
df5.reset_index(inplace=True)
df5

level_0      index   sec col   thr col   for col   fif col  sixth col
0        0    sec row -0.214863 -0.941346  2.304170  0.561030   0.443285
1        1    thr row -1.586326 -1.079067  2.338292  0.192024   0.439772
2        2    for row  0.620766  0.514160 -0.017655  0.198702   0.154176
3        3  fifth row  0.327749 -0.545991  2.078547  0.876584   0.461476

In [110]:
df5['new name'] = ['This','is','the','row']
df5


level_0      index   sec col   thr col   for col   fif col  sixth col  \
0        0    sec row -0.214863 -0.941346  2.304170  0.561030   0.443285   
1        1    thr row -1.586326 -1.079067  2.338292  0.192024   0.439772   
2        2    for row  0.620766  0.514160 -0.017655  0.198702   0.154176   
3        3  fifth row  0.327749 -0.545991  2.078547  0.876584   0.461476   

  new name  
0     This  
1       is  
2      the  
3      row

In [111]:
df5.set_index('new name',inplace=True)
df5


level_0      index   sec col   thr col   for col   fif col  \
new name                                                               
This            0    sec row -0.214863 -0.941346  2.304170  0.561030   
is              1    thr row -1.586326 -1.079067  2.338292  0.192024   
the             2    for row  0.620766  0.514160 -0.017655  0.198702   
row             3  fifth row  0.327749 -0.545991  2.078547  0.876584   

          sixth col  
new name             
This       0.443285  
is         0.439772  
the        0.154176  
row        0.461476

In [4]:
import pandas as pd
df1 = pd.DataFrame([1,2,3,4,5])
df2 = df1
A=id(df1)
B=id(df2)
if A==B:
    print("Same Location")
else:
    print("Different location")

Same Location


In [5]:

import numpy as RANGE
RANGE.arange(-0.8,0,0.2)

array([-0.8, -0.6, -0.4, -0.2])

In [9]:
data = {'prodID': ['101', '102', '103', '104', '104'],
'prodname': ['X', 'Y', 'Z', 'X', 'W'],
'profit': ['2738', '2727', '3497', '7347', '3743']}
df = pd.DataFrame(data, index=['one','two','three','four','five'])
print(df['prodname'][3])

X


In [10]:
A='This is a python quiz'
B= ' 2020'
D = A+B
print(D)

This is a python quiz 2020


In [11]:

Sample = ('This', 'Is', "Sample")
print(Sample[0])
Sample[1]="*"
print(Sample[1])


This


TypeError: 'tuple' object does not support item assignment